release:
  github:
    owner: digitalsleuth
    repo: cpcwin-salt
manifest:
  version: 2
  base: ""
  modes:
    - name: addon
      state: cpcwin.addon
      default: true
    - name: dedicated
      state: cpcwin.dedicated
      default: false
  supported_os:
    - id: windows
      release: 10
    - id: windows
      release: 11
