# This workflow should download the latest Get-ZimmermanTools installer,
# and compare the previous hash with the current hash. 

name: check-zimmerman-hash

on:
  schedule:
      - cron: "0 0 * * *"
  
  workflow_dispatch:
 
jobs:
  zimmerman_hash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Check Zimmerman Hash
        run: |
          wget https://f001.backblazeb2.com/file/EricZimmermanTools/Get-ZimmermanTools.zip
          PREVIOUS_HASH=$(cat /home/runner/work/cpcwin-salt/cpcwin-salt/cpcwin/standalones/zimmerman.sls | grep "set hash" | awk -F\' '{print $2}')
          CURRENT_HASH=$(sha256sum Get-ZimmermanTools.zip | awk '{print $1}')
          if [[ "$PREVIOUS_HASH" != "$CURRENT_HASH" ]]; then echo "HASH UPDATED - $CURRENT_HASH" && exit 1; else echo "No hash changes" && exit 0; fi
